#!/usr/bin/env bash
# Mock payloads for n8n → Google Sheets field mapping.
# Test webhook: click "Execute workflow" in n8n before EACH curl (one call per listen).
#
# Usage:
#   WEBHOOK_URL='https://n8n.jurojinpoker.com/webhook-test/...' ./scripts/n8n-webhook-mock.sh fok
#   WEBHOOK_URL='...' ./scripts/n8n-webhook-mock.sh all

set -euo pipefail

WEBHOOK_URL="${WEBHOOK_URL:-https://n8n.jurojinpoker.com/webhook-test/be1b19a3-b57d-4405-9f67-92c053cc440c}"
KIND="${1:-fok}"

post() {
  local name="$1"
  local body="$2"
  echo ">>> POST $name"
  curl -sS -X POST "$WEBHOOK_URL" \
    -H 'Content-Type: application/json' \
    -d "$body" \
    -w '\nHTTP %{http_code}\n\n'
}

MOCK_FOK='{
  "eventId": "mock-fok-001",
  "timestamp": "2026-06-09T15:50:12.970Z",
  "date": "2026-06-09",
  "hour": 15,
  "session": "us",
  "dayOfWeek": "Tuesday",
  "mode": "single-trade",
  "recordType": "TRADE_CLOSED_FOK",
  "skipReason": null,
  "marketId": "btc-updown-5m-1781016300",
  "side": "NO",
  "remainingSec": 3,
  "yesPrice": 0.01,
  "quotePrice": 0.5,
  "confidenceScore": 0.8125,
  "confidenceThreshold": 0.8,
  "pUp5m": 0.094,
  "trendScore": -0.3451,
  "emaSignal": -0.0645,
  "rsiValue": 0,
  "whaleSignal": 0,
  "whaleCount": 0,
  "llmBias": -0.5,
  "btcScore": -0.5547,
  "btcSnapshotStale": false,
  "entryAttempted": true,
  "entryOrderType": "FAK",
  "entryPriceQuote": 0.5,
  "entryPriceLimit": 0.55,
  "entryPriceReal": 0.52,
  "slippageEntry": 0.02,
  "sizeUsdPlanned": 1,
  "sizeUsdFilled": 1,
  "entryNotionalUsd": 1,
  "entryFeeUsd": 0.03,
  "entryCashOutUsd": 1.03,
  "entryOrderId": "0x526b13ea84e2f3cd33a7c8984ecd1d9c0e6063d2fc54960f07c173aa6f836f4d",
  "entryStatus": "matched",
  "entryErrorMsg": null,
  "entryAttemptCount": 1,
  "balanceUsdcAtEntry": 9.98,
  "exitMethod": "FOK",
  "exitOrderType": "FOK",
  "exitPriceQuote": 0.99,
  "exitPriceLimit": 0.01,
  "exitPriceReal": 0.99,
  "slippageExit": 0,
  "exitOrderId": "0x9114286c0a396e09bb98f76bb9232a04ff500e593deafdf1a633e4647c5f96cb",
  "exitStatus": "matched",
  "exitErrorMsg": null,
  "settlementOutcome": null,
  "balanceUsdcAtExit": 10.59,
  "pnlGross": 0.9,
  "polymarketFee": 0.29,
  "polymarketFeePct": 14.5,
  "pnlNet": 0.61,
  "walletDeltaUsd": 0.61,
  "executionStatus": "EXECUTED",
  "notes": "mock TRADE_CLOSED_FOK"
}'

MOCK_SETTLE='{
  "eventId": "mock-settle-002",
  "timestamp": "2026-06-09T15:35:12.284Z",
  "date": "2026-06-09",
  "hour": 15,
  "session": "us",
  "dayOfWeek": "Tuesday",
  "mode": "single-trade",
  "recordType": "TRADE_CLOSED_SETTLE",
  "skipReason": null,
  "marketId": "btc-updown-5m-1781019000",
  "side": "NO",
  "remainingSec": 290,
  "yesPrice": 0.4,
  "quotePrice": 0.5,
  "confidenceScore": 0.82,
  "confidenceThreshold": 0.8,
  "pUp5m": 0.092,
  "trendScore": -0.319,
  "emaSignal": -0.028,
  "rsiValue": 0,
  "whaleSignal": 0,
  "whaleCount": 0,
  "llmBias": -0.5,
  "btcScore": -0.592,
  "btcSnapshotStale": false,
  "entryAttempted": true,
  "entryOrderType": "FAK",
  "entryPriceQuote": 0.5,
  "entryPriceLimit": 0.55,
  "entryPriceReal": 0.36,
  "slippageEntry": -0.14,
  "sizeUsdPlanned": 1,
  "sizeUsdFilled": 1,
  "entryNotionalUsd": 1,
  "entryFeeUsd": 0.03,
  "entryCashOutUsd": 1.03,
  "entryOrderId": "0x1644ed4fac783a16153a2c4d75a70e435fb6a8504937f65ad3b99e4ac0ba3a6b",
  "entryStatus": "matched",
  "entryErrorMsg": null,
  "entryAttemptCount": 1,
  "balanceUsdcAtEntry": 8.98,
  "exitMethod": "SETTLE",
  "exitOrderType": null,
  "exitPriceQuote": null,
  "exitPriceLimit": 0.01,
  "exitPriceReal": 0,
  "slippageExit": 0,
  "exitOrderId": null,
  "exitStatus": "SELL_FAILED",
  "exitErrorMsg": "order could not be fully filled. FOK orders are fully filled or killed.",
  "settlementOutcome": "LOSS",
  "balanceUsdcAtExit": 7.95,
  "pnlGross": -1,
  "polymarketFee": 0.03,
  "polymarketFeePct": 1.5,
  "pnlNet": -1.03,
  "walletDeltaUsd": -1.03,
  "executionStatus": "EXECUTED",
  "notes": "mock TRADE_CLOSED_SETTLE"
}'

MOCK_FAK_FAIL='{
  "eventId": "mock-fak-fail-003",
  "timestamp": "2026-06-09T15:07:44.150Z",
  "date": "2026-06-09",
  "hour": 15,
  "session": "us",
  "dayOfWeek": "Tuesday",
  "mode": "single-trade",
  "recordType": "ENTRY_FAK_FAILED",
  "skipReason": null,
  "marketId": "btc-updown-5m-1781018700",
  "side": "YES",
  "remainingSec": 140,
  "yesPrice": 0.904,
  "quotePrice": 0.56,
  "confidenceScore": 0.81,
  "confidenceThreshold": 0.8,
  "pUp5m": 0.904,
  "trendScore": 0.379,
  "emaSignal": 0.112,
  "rsiValue": 100,
  "whaleSignal": 0,
  "whaleCount": 0,
  "llmBias": 0.65,
  "btcScore": 0.446,
  "btcSnapshotStale": false,
  "entryAttempted": true,
  "entryOrderType": "FAK",
  "entryPriceQuote": 0.56,
  "entryPriceLimit": 0.61,
  "entryPriceReal": null,
  "slippageEntry": null,
  "sizeUsdPlanned": 1,
  "sizeUsdFilled": 0,
  "entryNotionalUsd": null,
  "entryFeeUsd": null,
  "entryCashOutUsd": null,
  "entryOrderId": null,
  "entryStatus": "400",
  "entryErrorMsg": "no orders found to match with FAK order.",
  "entryAttemptCount": 3,
  "balanceUsdcAtEntry": 9.98,
  "exitMethod": null,
  "exitOrderType": null,
  "exitPriceQuote": null,
  "exitPriceLimit": null,
  "exitPriceReal": null,
  "slippageExit": null,
  "exitOrderId": null,
  "exitStatus": null,
  "exitErrorMsg": null,
  "settlementOutcome": null,
  "balanceUsdcAtExit": null,
  "pnlGross": null,
  "polymarketFee": null,
  "polymarketFeePct": null,
  "pnlNet": null,
  "walletDeltaUsd": null,
  "executionStatus": "EXECUTED",
  "notes": "mock ENTRY_FAK_FAILED"
}'

MOCK_SKIP='{
  "eventId": "mock-skip-004",
  "timestamp": "2026-06-09T15:02:27.586Z",
  "date": "2026-06-09",
  "hour": 15,
  "session": "us",
  "dayOfWeek": "Tuesday",
  "mode": "live",
  "recordType": "SIGNAL_SKIP",
  "skipReason": "LOW_CONFIDENCE",
  "marketId": "btc-updown-5m-1781016000",
  "side": "NO",
  "remainingSec": 155,
  "yesPrice": 0.845,
  "quotePrice": 0.155,
  "confidenceScore": 0.69,
  "confidenceThreshold": 0.8,
  "pUp5m": 0.155,
  "trendScore": -0.2,
  "emaSignal": -0.05,
  "rsiValue": 45,
  "whaleSignal": 0,
  "whaleCount": 0,
  "llmBias": -0.3,
  "btcScore": -0.1,
  "btcSnapshotStale": false,
  "entryAttempted": false,
  "entryOrderType": null,
  "entryPriceQuote": null,
  "entryPriceLimit": null,
  "entryPriceReal": null,
  "slippageEntry": null,
  "sizeUsdPlanned": 1,
  "sizeUsdFilled": null,
  "entryNotionalUsd": null,
  "entryFeeUsd": null,
  "entryCashOutUsd": null,
  "entryOrderId": null,
  "entryStatus": null,
  "entryErrorMsg": null,
  "entryAttemptCount": 0,
  "balanceUsdcAtEntry": null,
  "exitMethod": null,
  "exitOrderType": null,
  "exitPriceQuote": null,
  "exitPriceLimit": null,
  "exitPriceReal": null,
  "slippageExit": null,
  "exitOrderId": null,
  "exitStatus": null,
  "exitErrorMsg": null,
  "settlementOutcome": null,
  "balanceUsdcAtExit": null,
  "pnlGross": null,
  "polymarketFee": null,
  "polymarketFeePct": null,
  "pnlNet": null,
  "walletDeltaUsd": null,
  "executionStatus": "EXECUTED",
  "notes": "mock SIGNAL_SKIP"
}'

MOCK_MAKER_PAPER='{
  "recordType": "MAKER_DISLOCATION_PAPER",
  "mode": "PAPER",
  "lifecycle": "SETTLED",
  "eventId": "mock-maker-paper-001",
  "orderId": "paper-maker-mock-001",
  "timestamp": "2026-06-16T18:05:12.000Z",
  "marketId": "btc-updown-5m-1781016300",
  "side": "YES",
  "edge": 0.052,
  "limitPrice": 0.58,
  "filled": true,
  "pnlSimulated": 4.2,
  "fillPrice": 0.58,
  "sizeUsd": 100,
  "fairYes": 0.63,
  "yesPrice": 0.55,
  "deltaBtc": 0.0012
}'

case "$KIND" in
  fok) post TRADE_CLOSED_FOK "$MOCK_FOK" ;;
  settle) post TRADE_CLOSED_SETTLE "$MOCK_SETTLE" ;;
  fak) post ENTRY_FAK_FAILED "$MOCK_FAK_FAIL" ;;
  skip) post SIGNAL_SKIP "$MOCK_SKIP" ;;
  maker-paper) post MAKER_DISLOCATION_PAPER "$MOCK_MAKER_PAPER" ;;
  all)
    post TRADE_CLOSED_FOK "$MOCK_FOK"
    echo "Tip: re-click Execute workflow in n8n before each next call (test webhook)."
    ;;
  *)
    echo "Usage: $0 [fok|settle|fak|skip|maker-paper|all]"
    exit 1
    ;;
esac
